---
vhosts:
- name: slotogel
  main_domain: slotogelasia.com
  kawal_domains:
    - slotogelpro.com
    - slotogelmax.com
    - slotogelwin.com
  fresh_domains:
    - slotogelpro.xyz
    - slotogelmax.xyz
    - slotogelwin.xyz