---
vhosts:
- name: dash86
  main_domain: dashidn.co
  kawal_domains:
    - dashaktif24jam.com
    - dash88aktif24jam.com
    - dash88active.com
  fresh_domains:
    - dashslotidr.com
    - dash88slotidr.com
